apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString # Required
    value: "Endpoint=sb://msactiondapr.servicebus.windows.net/;SharedAccessKeyName=global;SharedAccessKey=QeJ
  - tpaperorders
  - tpaperdelivery